### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 0xfalls** [saintdaddy/Vare-Obfuscator2.0#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stub\Vare.py", line 100, in <module>
    VareObfuscator.obfuscate(args.file)
  File "C:\Users\Administrator\Desktop\stub\Vare.py", line 65, in obfuscate
    b = a.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

**Comment by passsa1337** [comment]
i guess u try to obfuscate the exe file, its for py files

**Comment by 0xfalls** [comment]
I did but after obfuscate, compiled to exe file didnt work

**Comment by passsa1337** [comment]
i can help if you tell me the error you get when you run the compiled exe
